plugins {
    alias libs.plugins.android.library
}

android {
    namespace = 'com.fongmi.android.tv.quickjs'

    compileSdk libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdk rootProject.minSdkLevel
        targetSdk libs.versions.targetSdk.get().toInteger()
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation project(':catvod')
    api libs.quickjs.android
    api libs.quickjs.java
    coreLibraryDesugaring libs.desugar
}